version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: entries
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - ./englishdictionary.sql:/docker-entrypoint-initdb.d/englishdictionary.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"